### PR TITLE
Fix redirect to proper ATutor installation

### PR DESCRIPTION
**Pull request by herat**

### CODE REVIEW

**Comment by herat** [comment]
@atutor Please take a look.

**Comment by atutor** [comment]
There seems to be a hard coded "http" which fails when the  redirect_uri is "https" You can try https on the demosite

Here's the message from google:
===

400. That’s an error.

Error: redirect_uri_mismatch

Application: ATutor Calendar

You can email the developer of this application at: heratgandhi@gmail.com

The redirect URI in the request, http://demo.atutorspaces.com/mods/_standard/calendar/google_connect_disconnect.php, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/717194602963.apps.googleusercontent.com?project=717194602963 to update the authorized redirect URIs.

**Comment by atutor** [comment]
Also, what's config is needed with a google developer account, so users do not need to connect to yours. A few words in the Admin Handbook would be helpful. 

Something like this:
https://demo.atutorspaces.com/documentation/admin/google_key.php?en

There should probably be an option to hide Google Calandar as an option if a key is not provided. 

thanks

**Comment by atutor** [comment]
Hi Herat, Anything more on this?

**Comment by herat** [comment]
_>There seems to be a hard coded "http" which fails when the redirect_uri is "https" You can try https on the demosite_

I was able to repro this. I made the change but it doesn't seem to be working. I need to investigate more into this.

_>Also, what config is needed with a google developer account, so users do not need to connect to yours. A few words in the Admin Handbook would be helpful.

Something like this:
https://demo.atutorspaces.com/documentation/admin/google_key.php?en

There should probably be an option to hide Google Calandar as an option if a key is not provided._

I realized this while I sent the first pull request. But it requires quite a lot of refactoring. Right now I am not sure I would be able to allocate that much of time. I will see if/how I can squeeze in this change.

**Comment by atutor** [comment]
Thanks Herat. See what you can do. Let me know if there are any issues.

**Comment by atutor** [comment]
Hi Herat,
I haven't heard from you in a while.  The Calendar seems to be in a bit of a broken state at the moment. Are you able to spend a little more time bring it to a functional level. I had a report, and confirmed myself, that shared calendars are no longer working, and when attempting to share within a course, it continues to report there are not people in a course to share with.

There's also the issue of setup a config page to setup a google API access token etc.

**Comment by herat** [comment]
It looks like I won't be able to spend more time on this. Sorry for the inconvenience but right now my schedule is really tight.

**Comment by atutor** [comment]
Sorry to hear that @herat . 
Can you give me a little guidance on how to best proceed from where you left off. 
thx

**Comment by herat** [comment]
sure, basically I fixed the basic authentication part using hardcoded google application. We need to allow users to create their own applications and feed those credentials into ATutor. After that, a review is needed to make sure no other API is broken as earlier I was using Zend library but now I moved to google library.

**Pull request merged**
