### PR TITLE
fixes content encoding error & enhancement options in search form

### PR DESCRIPTION
**Pull request by sudwebdesign**

### CODE REVIEW

**Comment by atutor** [comment]
Can you report the issue in mantis, and describe how to reproduce.  I'm not able to reproduce the problem you've described. Perhaps try to reproduce it on the demo site. Not sure why these variable are setup as arrays, but I'm guessing there was a reason. Just want to be able to reproduce, and ensure this does not break some other search function. thx

**Comment by atutor** [comment]
I'm going to dismiss this pull request. Have not been able to reprodcue the problem it is supposed to fix. Please confirm

**Comment by atutor** [comment]
I can't merge your pull request that fixes the foter problem on null search results. Please create a separate pull request, rather than adding it to the previous one, which is to be rejected. The issue the original pull request is supposed to fix, I cannot reproduce.

**Comment by sudwebdesign** [comment]
The problem of content encoding going only on my local web server, (Maybe an esoteric php version)
PHP:    5.5.6-1
MYSQL:    5.5.33-1
Linux 3.11-2-amd64

no problem online with php 5.6 but [search_within](https://github.com/atutor/ATutor/search?utf8=%E2%9C%93&q=search_within) algorithm in [search.inc.php](https://github.com/atutor/ATutor/blob/5df3ae6803667886a35e037fc0bcfd05ef03dce3/include/lib/search.inc.php) have no test if an array Only == and maybe more fast with not [] in query (my feeling, ATutor have chrono?)

ps: sorry for footer, have not added this in this MPR, are added automatically???

**Comment by sudwebdesign** [comment]
I suppress my repository and re-clone for re-push

**Pull request closed without merging**
