### PR TITLE
Replacing Zend framework with Google client library

### PR DESCRIPTION
**Pull request by herat**
http://imgur.com/a/DcqVM

### CODE REVIEW

**Comment by herat** [comment]
@gregrgay Please take a look when you get chance. Thanks!

**Comment by atutor** [comment]
I'm going to merge without testing. FYI I've updated your manits account to developer status, so you can work with the calendar related issues, send to herat_000@yahoo.co.in

**Comment by atutor** [comment]
There appears to be a hardcoded "ATutor" in the patch after going out to google calendar to approve access. Instead of returning to my atutorgit/ installation, it returns to another installation I have at ATutor/

**Comment by herat** [comment]
Sorry for some reason, I did not get notifications. ah, I will look into how to pass this dynamic redirect URI.

**Comment by atutor** [comment]
whats you correct email address?

**Comment by herat** [comment]
It (herat_000) is the correct one. I think I had disabled notifications on github in the past, now started getting notifications after enabling them and will look into issues reported on mantis in some order.

**Pull request merged**
